### ISSUE TITLE
[Bug] AssertionError with UniqueRenamer

### ISSUE THREAD

**Issue by lemmy** [konnov/apalache#149]
See TLA+ comments inside spec.

```tla
-------------------------- MODULE AsyncGameOfLife --------------------------
(***********************************************************************)
(* Evolution in Asynchronous Cellular Automata                         *)
(* by Chrystopher L. Nehaniv.                                          *)
(* https://uhra.herts.ac.uk/bitstream/handle/2299/7041/102007.pdf      *)
(***********************************************************************)
EXTENDS Integers,
        FiniteSets

\* CONSTANT N
N == 4
ASSUME N \in Nat

R == 
  {0,1,2}

Pos ==
  {<<x, y>> : x, y \in 1..N}  \* N initialized with CInit caused another issue, thus hardwired above.
nbhd(v) ==
  LET moore == {x \in {-1, 0, 1} \X {-1, 0, 1} : x /= <<0, 0>>}
      points == {<<v[1] + x, v[2] + y>> : <<x, y>> \in moore}
  IN { p \in points : /\ p[1] # 0 /\ p[2] # 0 
                      /\ p[1]<= N /\ p[2]<= N }

VARIABLES grid
vars == <<grid>>

TypeOK == 
  grid \in [Pos -> (BOOLEAN \X BOOLEAN \X R)]

Init == 
  grid \in [Pos -> (BOOLEAN \X BOOLEAN \X R)]

(* Original local transition function from the second page and 
   GameOfLife.tla. *)
delta(b, liveNbgrs) ==
  IF \/  (b /\ Cardinality(liveNbgrs) \in {2, 3})
     \/ (~b /\ Cardinality(liveNbgrs) = 3)
  THEN TRUE
  ELSE FALSE

ready(r, Neighbors) == 
  \A w \in Neighbors: grid[w][3] # (r + 2) % 3

qPP(qw, qwP, rw) == 
  CASE rw = 0 -> qw
    [] rw = 1 -> qwP
    [] OTHER -> FALSE \* Undefined in paper, but apalache demands it.

(* Transition function from third page. *)  
deltaP(v, q, qP, r, Neighbors) ==
  \/ /\ r = 0
     /\ ready(0, Neighbors) 
     /\ grid' = [ grid EXCEPT ![v] = <<delta(q, 
                  {w \in Neighbors: qPP(grid[w][1], grid[w][2], grid[w][3])}),
                  q, 1>> ]
  \/ /\ r = 0
     /\ ~ ready(0, Neighbors) 
     /\ grid' = [ grid EXCEPT ![v] = <<q, qP, 0>> ]
  \/ /\ r \in {1,2}
     /\ ready(r, Neighbors)
     /\ grid' = [ grid EXCEPT ![v] = <<q, qP, (r + 1) % 3>> ]
  \/ /\ r \in {1,2}
     /\ ~ ready(r, Neighbors)
     /\ UNCHANGED grid

\* Dummy Next that still reproduces the assertionerror (appears related to def of nbhd above).
Next == deltaP(<<1,1>>, grid[<<1,1>>][1], grid[<<1,1>>][2], grid[<<1,1>>][3], nbhd(<<1,1>>))
=========
```

```
markus@avocado:~/src/TLA/_community/apalache(master)$ bin/apalache-mc check AsyncGameOfLife.tla
# Tool home: /home/markus/src/TLA/_community/apalache
# Package:   /home/markus/src/TLA/_community/apalache/mod-distribution/target/apalache-pkg-0.6.1-SNAPSHOT-full.jar
# JVM args: -Xmx4096m -Djava.library.path=/home/markus/src/TLA/_community/apalache/3rdparty/lib
#
# APALACHE version 0.6.1-SNAPSHOT build v0.6.0-15-gf27dcd8
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/konnov/apalache/issues]

Checker options: filename=AsyncGameOfLife.tla, init=Init, next=Next, inv= I@14:31:06.012
PASS #0: SanyParser                                               I@14:31:06.332
Parsing file /home/markus/src/TLA/_community/apalache/AsyncGameOfLife.tla
Parsing file /tmp/Integers.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/Sequences.tla
PASS #1: ConfigurationPass                                        I@14:31:06.715
PASS #2: InlinePass                                               I@14:31:06.744
  > InlinerOfUserOper                                             I@14:31:06.750
  > LetInExpander                                                 I@14:31:06.789
PASS #3: PrimingPass                                              I@14:31:06.845
  > Introducing InitPrimed for Init'                              I@14:31:06.849
PASS #4: VCGen                                                    I@14:31:06.892
  > No invariant given. Only deadlocks will be checked            I@14:31:06.893
PASS #5: PreprocessingPass                                        I@14:31:06.918
  > Before preprocessing: unique renaming                         I@14:31:06.918
 > Applying standard transformations:                             I@14:31:06.928
  > Desugarer                                                     I@14:31:06.929
  > UniqueRenamer                                                 I@14:31:06.958
(This should not have happened, but it did. REPORT IT: [https://github.com/konnov/apalache/issues],java.lang.AssertionError: assertion failed)
Unhandled exception                                               E@14:31:07.001
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:204)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:188)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$6(IncrementalRenaming.scala:235)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:225)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:177)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:204)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:204)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:204)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:204)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:204)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:204)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:932)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:204)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:204)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:204)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$rename$1(IncrementalRenaming.scala:204)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$track$1(TrackerWithListeners.scala:15)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.apply(IncrementalRenaming.scala:249)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$applyToDecl$1(IncrementalRenaming.scala:250)
	at at.forsyte.apalache.tla.lir.transformations.impl.Lift$.$anonfun$exToDecl$1(Lift.scala:8)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.lir.transformations.impl.Lift$.$anonfun$declToDecls$1(Lift.scala:13)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.syncAndNormalizeDs(IncrementalRenaming.scala:377)
	at at.forsyte.apalache.tla.lir.transformations.standard.IncrementalRenaming.$anonfun$renameInModule$1(IncrementalRenaming.scala:134)
	at at.forsyte.apalache.tla.pp.passes.PreproPassImpl.$anonfun$execute$1(PreproPassImpl.scala:60)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at at.forsyte.apalache.tla.pp.passes.PreproPassImpl.execute(PreproPassImpl.scala:57)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:23)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:38)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:118)
	at at.forsyte.apalache.tla.Tool$.$anonfun$main$2(Tool.scala:57)
	at at.forsyte.apalache.tla.Tool$.$anonfun$main$2$adapted(Tool.scala:57)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:167)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:57)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  1 sec                          I@14:31:07.004
Total time: 1.62 sec                                              I@14:31:07.004
```

**Comment by konnov** [comment]
Hi Markus,

Your example has triggered two bugs in two independent pieces of the preprocessor. In both cases, `<<x, y>> \in moore` was preprocessed incorrectly. I have fixed it in `unstable`. Either build a version from `unstable` or wait until we build a docker image (Wednesday).

After the fix, apalache runs without any problems for 10 steps. Is it the expected outcome?

```
Step 0, level 0: checking if 1 transition(s) are enabled and violate the invariant I@23:47:41.726
Step 0, level 1: collecting 1 enabled transition(s)               I@23:47:42.076
Step 1, level 1: checking if 4 transition(s) are enabled and violate the invariant I@23:47:42.245
Step 1, level 2: collecting 4 enabled transition(s)               I@23:47:44.398
Step 2, level 2: checking if 4 transition(s) are enabled and violate the invariant I@23:47:46.191
Step 2, level 3: collecting 4 enabled transition(s)               I@23:47:48.191
Step 3, level 3: checking if 4 transition(s) are enabled and violate the invariant I@23:47:49.853
Step 3, level 4: collecting 2 enabled transition(s)               I@23:47:53.595
Step 4, level 4: checking if 4 transition(s) are enabled and violate the invariant I@23:47:53.897
Step 4, level 5: collecting 2 enabled transition(s)               I@23:47:56.838
Step 5, level 5: checking if 4 transition(s) are enabled and violate the invariant I@23:47:57.053
Step 5, level 6: collecting 2 enabled transition(s)               I@23:47:59.843
Step 6, level 6: checking if 4 transition(s) are enabled and violate the invariant I@23:48:00.071
Step 6, level 7: collecting 2 enabled transition(s)               I@23:48:03.024
Step 7, level 7: checking if 4 transition(s) are enabled and violate the invariant I@23:48:03.278
Step 7, level 8: collecting 2 enabled transition(s)               I@23:48:06.516
Step 8, level 8: checking if 4 transition(s) are enabled and violate the invariant I@23:48:06.754
Step 8, level 9: collecting 2 enabled transition(s)               I@23:48:09.521
Step 9, level 9: checking if 4 transition(s) are enabled and violate the invariant I@23:48:09.763
Step 9, level 10: collecting 2 enabled transition(s)              I@23:48:13.390
Step 10, level 10: checking if 4 transition(s) are enabled and violate the invariant I@23:48:13.683
Step 10, level 11: collecting 2 enabled transition(s)             I@23:48:17.236
The outcome is: NoError                                           I@23:48:17.565
PASS #11: Terminal                                                I@23:48:17.565
Checker reports no error up to computation length 10              I@23:48:17.566
It took me 0 days  0 hours  0 min 37 sec                          I@23:48:17.566
Total time: 37.760 sec                                            I@23:48:17.566
EXITCODE: OK
```

**Comment by lemmy** [comment]
With the [actual spec](https://github.com/konnov/apalache/issues/150#issue-644209150) apalache becomes extremely slow after ~8 steps (TLC below).

```bash
markus@makuppe-z440:~/apalache$ bin/apalache-mc check --init=BlockInit AsyncGameOfLife.tla
# Tool home: /home/markus/apalache
# Package:   /home/markus/apalache/mod-distribution/target/apalache-pkg-0.7.0-SNAPSHOT-full.jar
# JVM args: -Xmx4096m -Djava.library.path=/home/markus/apalache/3rdparty/lib
#
# APALACHE version 0.7.0-SNAPSHOT build v0.6.0-125-g1918dfc
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/konnov/apalache/issues]

Checker options: filename=AsyncGameOfLife.tla, init=BlockInit, next=, inv= I@19:50:11.587
PASS #0: SanyParser                                               I@19:50:11.885
Parsing file /home/markus/apalache/AsyncGameOfLife.tla
Parsing file /tmp/Integers.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/Sequences.tla
Parsing file /tmp/Naturals.tla
PASS #1: ConfigurationPass                                        I@19:50:12.320
  > Loading TLC configuration from AsyncGameOfLife.cfg            I@19:50:12.321
  > No TLC configuration found; skipping                          I@19:50:12.327
PASS #2: UnrollPass                                               I@19:50:12.375
  > Unroller                                                      I@19:50:12.379
PASS #3: InlinePass                                               I@19:50:12.413
  > InlinerOfUserOper                                             I@19:50:12.414
  > LetInExpander                                                 I@19:50:12.452
PASS #4: PrimingPass                                              I@19:50:12.495
  > Introducing BlockInitPrimed for BlockInit'                    I@19:50:12.499
PASS #5: VCGen                                                    I@19:50:12.536
  > No invariant given. Only deadlocks will be checked            I@19:50:12.536
PASS #6: PreprocessingPass                                        I@19:50:12.558
  > Before preprocessing: unique renaming                         I@19:50:12.558
 > Applying standard transformations:                             I@19:50:12.565
  > Desugarer                                                     I@19:50:12.566
  > UniqueRenamer                                                 I@19:50:12.590
  > Normalizer                                                    I@19:50:12.656
  > Keramelizer                                                   I@19:50:12.663
  > After preprocessing: UniqueRenamer                            I@19:50:12.713
PASS #7: TransitionFinderPass                                     I@19:50:12.784
  > Found 1 initializing transitions                              I@19:50:12.878
  > Found 4 transitions                                           I@19:50:12.912
  > No constant initializer                                       I@19:50:12.913
  > Applying unique renaming                                      I@19:50:12.913
PASS #8: OptimizationPass                                         I@19:50:12.935
 > Applying optimizations:                                        I@19:50:12.939
  > ConstSimplifier                                               I@19:50:12.940
  > ExprOptimizer                                                 I@19:50:12.947
  > ConstSimplifier                                               I@19:50:12.971
PASS #9: AnalysisPass                                             I@19:50:12.996
 > Marking skolemizable existentials and sets to be expanded...   I@19:50:12.998
  > SkolemizationMarker                                           I@19:50:13.000
  > ExpansionMarker                                               I@19:50:13.005
 > Running analyzers...                                           I@19:50:13.018
  > Introduced expression grades                                  I@19:50:13.038
  > Introduced 1 formula hints                                    I@19:50:13.038
PASS #10: BoundedChecker                                          I@19:50:13.038
No CONSTANT initializer given                                     I@19:50:13.102
Step 0, level 0: checking if 1 transition(s) are enabled and violate the invariant I@19:50:13.107
Step 0, level 1: collecting 1 enabled transition(s)               I@19:50:13.265
Step 1, level 1: checking if 4 transition(s) are enabled and violate the invariant I@19:50:13.328
Step 1, level 2: collecting 1 enabled transition(s)               I@19:50:14.892
Step 2, level 2: checking if 4 transition(s) are enabled and violate the invariant I@19:50:15.542
Step 2, level 3: collecting 2 enabled transition(s)               I@19:50:17.566
Step 3, level 3: checking if 4 transition(s) are enabled and violate the invariant I@19:50:18.457
Step 3, level 4: collecting 2 enabled transition(s)               I@19:50:21.428
Step 4, level 4: checking if 4 transition(s) are enabled and violate the invariant I@19:50:22.350
Step 4, level 5: collecting 2 enabled transition(s)               I@19:50:32.048
Step 5, level 5: checking if 4 transition(s) are enabled and violate the invariant I@19:50:32.907
Step 5, level 6: collecting 3 enabled transition(s)               I@19:50:54.506
Step 6, level 6: checking if 4 transition(s) are enabled and violate the invariant I@19:50:55.586
Step 6, level 7: collecting 3 enabled transition(s)               I@19:51:55.882
Step 7, level 7: checking if 4 transition(s) are enabled and violate the invariant I@19:51:57.238
Step 7, level 8: collecting 3 enabled transition(s)               I@19:58:21.970
Step 8, level 8: checking if 4 transition(s) are enabled and violate the invariant I@19:58:23.149
Step 8, level 9: collecting 3 enabled transition(s)               I@21:18:59.484
Step 9, level 9: checking if 4 transition(s) are enabled and violate the invariant I@21:19:00.614
...
```

```bash
TLC2 Version 2.15 of Day Month 20?? (rev: b735728)
Running breadth-first search Model-Checking with fp 22 and seed 1330746266887846075 with 1 worker on 4 cores with 1764MB heap and 3966MB offheap memory [pid: 285379] (Linux 5.4.0-37-generic amd64, AdoptOpenJDK 14.0.1 x86_64, OffHeapDiskFPSet, DiskStateQueue).
Starting SANY...
Parsing file /home/markus/src/TLA/_specs/models/realworld/tlaplus_specs/AsyncGameOfLife.toolbox/Block/MC.tla
Parsing file /home/markus/src/TLA/_specs/models/realworld/tlaplus_specs/AsyncGameOfLife.toolbox/Block/AsyncGameOfLife.tla
Parsing file /opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.202006230404/tla2sany/StandardModules/TLC.tla
Parsing file /opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.202006230404/tla2sany/StandardModules/Integers.tla
Parsing file /opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.202006230404/tla2sany/StandardModules/FiniteSets.tla
Parsing file /opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.202006230404/tla2sany/StandardModules/Naturals.tla
Parsing file /opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.202006230404/tla2sany/StandardModules/Sequences.tla
Semantic processing of module Naturals
Semantic processing of module Integers
Semantic processing of module Sequences
Semantic processing of module FiniteSets
Semantic processing of module AsyncGameOfLife
Semantic processing of module TLC
Semantic processing of module MC
SANY finished.
Starting... (2020-06-23 20:06:48)
Computing initial states...
Finished computing initial states: 1 distinct state generated at 2020-06-23 20:06:51.
Progress(8) at 2020-06-23 20:06:54: 133,995 states generated (133,995 s/min), 18,032 distinct states found (18,032 ds/min), 9,659 states left on queue.
Progress(35) at 2020-06-23 20:07:54: 4,881,755 states generated (4,747,760 s/min), 313,696 distinct states found (295,664 ds/min), 8,586 states left on queue.
Model checking completed. No error has been found.
  Estimates of the probability that TLC did not check all reachable states
  because two distinct states had the same fingerprint:
  calculated (optimistic):  val = 2.4E-7
  based on the actual fingerprints:  val = 5.4E-10
Progress(67) at 2020-06-23 20:08:52: 8,639,953 states generated (4,158,788 s/min), 539,997 distinct states found (259,924 ds/min), 0 states left on queue.
8639953 states generated, 539997 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 67.
The average outdegree of the complete state graph is 1 (minimum is 0, the maximum 16 and the 95th percentile is 4).
Finished in 124668ms at (2020-06-23 20:08:52)
```

**Comment by andrey-kuprianov** [comment]
published the unstable docker image; feel free to use

**Comment by lemmy** [comment]
FWIW: Re-ran with most recent Apalache from `unstable` and runtime is reduced from ~17h to ~16h.

```tla
makuppe@makuppe-z440:/mnt/e$ /mnt/e/apalache/bin/apalache-mc check --init=BlockInit AsyncGameOfLife.tla
# Tool home: /mnt/e/apalache
# Package:   /mnt/e/apalache/mod-distribution/target/apalache-pkg-0.7.3-SNAPSHOT-full.jar
# JVM args: -Xmx4096m -DTLA-Library=/mnt/e/apalache/src/tla
#
# APALACHE version 0.7.3-SNAPSHOT build v0.7.0-107-g03fdeff
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]

Checker options: filename=AsyncGameOfLife.tla, init=BlockInit, next=, inv= I@15:13:48.707
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/mnt/e/apalache/mod-distribution/target/apalache-pkg-0.7.3-SNAPSHOT-full.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
PASS #0: SanyParser                                               I@15:13:49.323
Parsing file /mnt/e/AsyncGameOfLife.tla
Parsing file /tmp/Integers.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/Sequences.tla
PASS #1: ConfigurationPass                                        I@15:13:49.998
  > AsyncGameOfLife.cfg: Loading TLC configuration                I@15:13:50.001
  > No TLC configuration found. Skipping.                         I@15:13:50.018
  > Command line option --next is not set. Using Next             I@15:13:50.018
  > Set the initialization predicate to BlockInit                 I@15:13:50.018
  > Set the transition predicate to Next                          I@15:13:50.020
PASS #2: UnrollPass                                               I@15:13:50.081
  > Unroller                                                      I@15:13:50.085
PASS #3: PrimingPass                                              I@15:13:50.114
  > Introducing BlockInitPrimed for BlockInit'                    I@15:13:50.118
PASS #4: CoverAnalysisPass                                        I@15:13:50.146
PASS #5: InlinePass                                               I@15:13:50.148
  > InlinerOfUserOper                                             I@15:13:50.150
  > LetInExpander                                                 I@15:13:50.184
  > InlinerOfUserOper                                             I@15:13:50.190
Leaving only relevant operators: BlockInit, BlockInitPrimed, CInitPrimed, Next I@15:13:50.194
PASS #6: VCGen                                                    I@15:13:50.226
  > No invariant given. Only deadlocks will be checked            I@15:13:50.226
PASS #7: PreprocessingPass                                        I@15:13:50.244
  > Before preprocessing: unique renaming                         I@15:13:50.245
 > Applying standard transformations:                             I@15:13:50.255
  > Desugarer                                                     I@15:13:50.256
  > UniqueRenamer                                                 I@15:13:50.304
  > Normalizer                                                    I@15:13:50.377
  > Keramelizer                                                   I@15:13:50.404
  > After preprocessing: UniqueRenamer                            I@15:13:50.440
PASS #8: TransitionFinderPass                                     I@15:13:50.478
  > Found 1 initializing transitions                              I@15:13:51.236
  > Found 4 transitions                                           I@15:13:51.294
  > No constant initializer                                       I@15:13:51.295
  > Applying unique renaming                                      I@15:13:51.297
PASS #9: OptimizationPass                                         I@15:13:51.331
 > Applying optimizations:                                        I@15:13:51.337
  > ConstSimplifier                                               I@15:13:51.338
  > ExprOptimizer                                                 I@15:13:51.345
  > ConstSimplifier                                               I@15:13:51.367
PASS #10: AnalysisPass                                            I@15:13:51.398
 > Marking skolemizable existentials and sets to be expanded...   I@15:13:51.401
  > SkolemizationMarker                                           I@15:13:51.402
  > ExpansionMarker                                               I@15:13:51.404
 > Running analyzers...                                           I@15:13:51.415
  > Introduced expression grades                                  I@15:13:51.438
  > Introduced 1 formula hints                                    I@15:13:51.439
PASS #11: BoundedChecker                                          I@15:13:51.440
No CONSTANT initializer given                                     I@15:13:51.504
Step 0, level 0: checking if 1 transition(s) are enabled and violate the invariant I@15:13:51.516
Step 0, level 1: collecting 1 enabled transition(s)               I@15:13:51.850
Step 1, level 1: checking if 4 transition(s) are enabled and violate the invariant I@15:13:51.968
Step 1, level 2: collecting 1 enabled transition(s)               I@15:13:53.343
Step 2, level 2: checking if 4 transition(s) are enabled and violate the invariant I@15:13:53.679
Step 2, level 3: collecting 2 enabled transition(s)               I@15:13:54.868
Step 3, level 3: checking if 4 transition(s) are enabled and violate the invariant I@15:13:55.324
Step 3, level 4: collecting 2 enabled transition(s)               I@15:13:59.249
Step 4, level 4: checking if 4 transition(s) are enabled and violate the invariant I@15:13:59.553
Step 4, level 5: collecting 2 enabled transition(s)               I@15:14:07.762
Step 5, level 5: checking if 4 transition(s) are enabled and violate the invariant I@15:14:08.059
Step 5, level 6: collecting 3 enabled transition(s)               I@15:14:31.442
Step 6, level 6: checking if 4 transition(s) are enabled and violate the invariant I@15:14:31.842
Step 6, level 7: collecting 3 enabled transition(s)               I@15:15:49.027
Step 7, level 7: checking if 4 transition(s) are enabled and violate the invariant I@15:15:49.404
Step 7, level 8: collecting 3 enabled transition(s)               I@15:22:02.216
Step 8, level 8: checking if 4 transition(s) are enabled and violate the invariant I@15:22:02.661
Step 8, level 9: collecting 3 enabled transition(s)               I@16:10:36.381
Step 9, level 9: checking if 4 transition(s) are enabled and violate the invariant I@16:10:36.859
Step 9, level 10: collecting 3 enabled transition(s)              I@20:11:44.929
Step 10, level 10: checking if 4 transition(s) are enabled and violate the invariant I@20:11:45.374
Step 10, level 11: collecting 3 enabled transition(s)             I@07:36:06.363
The outcome is: NoError                                           I@07:36:06.964
PASS #12: Terminal                                                I@07:36:06.965
Checker reports no error up to computation length 10              I@07:36:06.966
It took me 0 days 16 hours 22 min 18 sec                          I@07:36:06.967
Total time: 58938.406 sec                                         I@07:36:06.967
EXITCODE: OK
```
