### ISSUE TITLE
Multicore version does not gracefully terminate

### ISSUE THREAD

**Issue by lemmy** [konnov/apalache#87]
```bash
markus@avocado:~/src/TLA/_community/apalache(ik/multicore)$ export TMPDIR=. && time bin/apalache-mc check --init=Init --cinit=ConstInit --next=Next --length=50 --inv=Inv --nworkers=4 BlockingQueue.tla
# Tool home: /home/markus/src/TLA/_community/apalache
# Package:   /home/markus/src/TLA/_community/apalache/apalache-pkg-0.6.0-SNAPSHOT-full.jar
# JVM args: -Xmx4096m
#
# APALACHE version 0.6.0-SNAPSHOT build 0.5.0-289-gab39edc
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/konnov/apalache/issues]

Checker options: filename=BlockingQueue.tla, init=Init, next=Next, inv=Inv I@091409.536
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/markus/src/TLA/_community/apalache/apalache-pkg-0.6.0-SNAPSHOT-full.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
PASS #0: SanyParser                                                 I@091409.928
Parsing file /home/markus/src/TLA/_community/apalache/BlockingQueue.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/Sequences.tla
Parsing file /tmp/FiniteSets.tla
PASS #1: ConfigurationPass                                          I@091410.256
PASS #2: InlinePass                                                 I@091410.280
  > InlinerOfUserOper                                               I@091410.286
  > LetInExpander                                                   I@091410.308
PASS #3: PrimingPass                                                I@091410.336
  > Introducing ConstInitPrimed for ConstInit'                      I@091410.339
  > Introducing InitPrimed for Init'                                I@091410.342
PASS #4: VCGen                                                      I@091410.369
  > Producing verification conditions from the invariant Inv        I@091410.369
  > VCGen produced 1 verification condition(s)                      I@091410.371
PASS #5: PreprocessingPass                                          I@091410.397
  > Before preprocessing: unique renaming                           I@091410.397
 > Applying standard transformations:                               I@091410.406
  > Desugarer                                                       I@091410.406
  > UniqueRenamer                                                   I@091410.416
  > Normalizer                                                      I@091410.472
  > Keramelizer                                                     I@091410.480
  > PrimedEqualityToMembership                                      I@091410.495
  > After preprocessing: UniqueRenamer                              I@091410.500
PASS #6: TransitionFinderPass                                       I@091410.555
  > Found 1 initializing transitions                                I@091410.658
  > Found 6 transitions                                             I@091410.728
  > Found constant initializer ConstInit                            I@091410.728
  > Applying unique renaming                                        I@091410.729
PASS #7: OptimizationPass                                           I@091410.767
 > Applying optimizations:                                          I@091410.773
  > ExprOptimizer                                                   I@091410.774
  > ConstSimplifier                                                 I@091410.782
PASS #8: AnalysisPass                                               I@091410.806
  > Introduced expression grades                                    I@091410.835
  > Found 8 skolemizable existentials                               I@091410.836
  > Introduced 31 formula hints                                     I@091410.836
PASS #9: BoundedChecker                                             I@091410.837
Worker 3 is initializing                                            I@091410.934
Worker 2 is initializing                                            I@091410.934
Worker 4 is initializing                                            I@091410.934
Worker 1 is initializing                                            I@091410.934
Worker 1: Initializing CONSTANTS with the provided operator         I@091410.935
Worker 1 started                                                    I@091410.998
Worker 3 started                                                    I@091410.998
Worker 2 started                                                    I@091410.998
Worker 4 started                                                    I@091410.998
Worker 1: CLOSING NODE 0                                            I@091411.063
Worker 1: Step 0, level 0: collecting 1 enabled transition(s)       I@091411.076
Worker 1: INTRODUCED NODE 1 with 6 open transitions                 I@091411.093
Worker 1: CLOSING NODE 1                                            I@091411.425
Worker 1: Step 1, level 0: collecting 2 enabled transition(s)       I@091411.436
Worker 1: INTRODUCED NODE 2 with 6 open transitions                 I@091411.493
Worker 3: CLOSING NODE 2                                            I@091411.713
Worker 3: Step 2, level 0: collecting 4 enabled transition(s)       I@091411.740
Worker 3: INTRODUCED NODE 3 with 6 open transitions                 I@091411.798
Worker 4: CLOSING NODE 3                                            I@091412.090
Worker 4: Step 3, level 0: collecting 4 enabled transition(s)       I@091412.142
Worker 4: INTRODUCED NODE 4 with 6 open transitions                 I@091412.186
Worker 3: CLOSING NODE 4                                            I@091412.468
Worker 3: Step 4, level 0: collecting 6 enabled transition(s)       I@091412.521
Worker 3: INTRODUCED NODE 5 with 6 open transitions                 I@091412.591
Worker 3: CLOSING NODE 5                                            I@091412.987
Worker 3: Step 5, level 0: collecting 6 enabled transition(s)       I@091413.050
Worker 3: INTRODUCED NODE 6 with 6 open transitions                 I@091413.130
Worker 4: CLOSING NODE 6                                            I@091413.572
Worker 4: Step 6, level 0: collecting 6 enabled transition(s)       I@091413.644
Worker 4: INTRODUCED NODE 7 with 6 open transitions                 I@091413.703
Worker 3: CLOSING NODE 7                                            I@091414.218
Worker 3: Step 7, level 0: collecting 6 enabled transition(s)       I@091414.262
Worker 3: INTRODUCED NODE 8 with 6 open transitions                 I@091414.312
Worker 1: CLOSING NODE 8                                            I@091414.788
Worker 1: Step 8, level 0: collecting 6 enabled transition(s)       I@091414.846
Worker 1: INTRODUCED NODE 9 with 6 open transitions                 I@091414.892
Worker 4: CLOSING NODE 9                                            I@091415.551
Worker 4: Step 9, level 0: collecting 6 enabled transition(s)       I@091415.650
Worker 4: INTRODUCED NODE 10 with 6 open transitions                I@091415.705
Worker 2: CLOSING NODE 10                                           I@091416.393
Worker 2: Step 10, level 0: collecting 6 enabled transition(s)      I@091416.495
Worker 2: INTRODUCED NODE 11 with 6 open transitions                I@091416.548
Worker 1: CLOSING NODE 11                                           I@091417.398
Worker 1: Step 11, level 0: collecting 6 enabled transition(s)      I@091417.515
Worker 1: INTRODUCED NODE 12 with 6 open transitions                I@091417.574
Worker 1: CLOSING NODE 12                                           I@091418.620
Worker 1: Step 12, level 0: collecting 6 enabled transition(s)      I@091418.717
Worker 1: INTRODUCED NODE 13 with 6 open transitions                I@091418.789
Worker 3: CLOSING NODE 13                                           I@091420.124
Worker 3: Step 13, level 0: collecting 6 enabled transition(s)      I@091420.289
Worker 3: INTRODUCED NODE 14 with 6 open transitions                I@091420.369
Worker 4: CLOSING NODE 14                                           I@091422.434
Worker 4: Step 14, level 0: collecting 6 enabled transition(s)      I@091422.658
Worker 4: INTRODUCED NODE 15 with 6 open transitions                I@091422.881
Worker 2: CLOSING NODE 15                                           I@091425.429
Worker 2: Step 15, level 0: collecting 6 enabled transition(s)      I@091425.764
Worker 2: INTRODUCED NODE 16 with 6 open transitions                I@091425.944
Worker 1: CLOSING NODE 16                                           I@091428.764
Worker 1: Step 16, level 0: collecting 6 enabled transition(s)      I@091429.035
Worker 1: INTRODUCED NODE 17 with 6 open transitions                I@091429.240
Worker 1: CLOSING NODE 17                                           I@091657.192
Worker 1: Step 17, level 0: collecting 6 enabled transition(s)      I@091657.349
Worker 1: INTRODUCED NODE 18 with 6 open transitions                I@091657.404
Worker 1: CLOSING NODE 18                                           I@091659.170
Worker 1: Step 18, level 0: collecting 6 enabled transition(s)      I@091659.406
Worker 1: INTRODUCED NODE 19 with 6 open transitions                I@091659.498
Worker 3: CLOSING NODE 19                                           I@091701.889
Worker 3: Step 19, level 0: collecting 6 enabled transition(s)      I@091702.116
Worker 3: INTRODUCED NODE 20 with 6 open transitions                I@091702.215
Worker 4: CLOSING NODE 20                                           I@091706.046
Worker 4: Step 20, level 0: collecting 6 enabled transition(s)      I@091706.615
Worker 4: INTRODUCED NODE 21 with 6 open transitions                I@091706.804
^CUnable find the source of the problematic expression                E@091752.736
Worker 4 has thrown an exception                                    E@091752.738
at.forsyte.apalache.tla.bmcmt.SmtEncodingException: SMT 172: z3 reports UNKNOWN. Maybe, your specification is outside the supported logic.
	at at.forsyte.apalache.tla.bmcmt.smt.Z3SolverContext.sat(Z3SolverContext.scala:325)
	at at.forsyte.apalache.tla.bmcmt.smt.Z3SolverContext.satOrTimeout(Z3SolverContext.scala:332)
	at at.forsyte.apalache.tla.bmcmt.smt.RecordingZ3SolverContext.satOrTimeout(RecordingZ3SolverContext.scala:208)
	at at.forsyte.apalache.tla.bmcmt.ModelChecker.checkOneInvariant(ModelChecker.scala:866)
	at at.forsyte.apalache.tla.bmcmt.ModelChecker.proveOneCondition(ModelChecker.scala:359)
	at at.forsyte.apalache.tla.bmcmt.ModelChecker.searchLoop(ModelChecker.scala:161)
	at at.forsyte.apalache.tla.bmcmt.ModelChecker.run(ModelChecker.scala:94)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl$$anon$1.run(BoundedCheckerPassImpl.scala:81)
Shutdown hook activated. Interrupting the workers and joining them for 5000 ms. E@091752.740
^CUnable find the source of the problematic expression                E@091804.628
Worker 3 has thrown an exception                                    E@091804.628
at.forsyte.apalache.tla.bmcmt.SmtEncodingException: SMT 164: z3 reports UNKNOWN. Maybe, your specification is outside the supported logic.
	at at.forsyte.apalache.tla.bmcmt.smt.Z3SolverContext.sat(Z3SolverContext.scala:325)
	at at.forsyte.apalache.tla.bmcmt.smt.Z3SolverContext.satOrTimeout(Z3SolverContext.scala:332)
	at at.forsyte.apalache.tla.bmcmt.smt.RecordingZ3SolverContext.satOrTimeout(RecordingZ3SolverContext.scala:208)
	at at.forsyte.apalache.tla.bmcmt.ModelChecker.checkOneInvariant(ModelChecker.scala:866)
	at at.forsyte.apalache.tla.bmcmt.ModelChecker.proveOneCondition(ModelChecker.scala:359)
	at at.forsyte.apalache.tla.bmcmt.ModelChecker.searchLoop(ModelChecker.scala:161)
	at at.forsyte.apalache.tla.bmcmt.ModelChecker.run(ModelChecker.scala:94)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl$$anon$1.run(BoundedCheckerPassImpl.scala:81)
^C#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2ee995a1ac, pid=27034, tid=27034
#
# JRE version: OpenJDK Runtime Environment (11.0.5+10) (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)
# Java VM: OpenJDK 64-Bit Server VM (11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libz3.so+0x11651ac]  on_ctrl_c(int)+0x1c
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/markus/src/TLA/_community/apalache/core.27034)
#
# An error report file with more information is saved as:
# /home/markus/src/TLA/_community/apalache/hs_err_pid27034.log
#
# If you would like to submit a bug report, please visit:
#   Unknown
#
^C^C

```

[hs_err_pid27034.log](https://github.com/konnov/apalache/files/4092456/hs_err_pid27034.log)

**Comment by konnov** [comment]
It should work terminate correctly now. If it does not, reopen the issue.
